name: Tourism Project Pipeline

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r tourism_project/requirements.txt

      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python tourism_project/model_building/data_register.py

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r tourism_project/requirements.txt

      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python tourism_project/model_building/prep_2.py

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r tourism_project/requirements.txt

      - name: Model Training and Registration
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python tourism_project/model_building/train.py --model_version model_0
          python tourism_project/model_building/train.py --model_version model_1
          python tourism_project/model_building/train.py --model_version model_2

  model-comparison:
    needs: model-training
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r tourism_project/requirements.txt

      - name: Evaluate and Promote Champion Model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python tourism_project/model_building/compare_models.py

  deploy-hosting:
    needs: [model-comparison, data-prep, register-dataset]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r tourism_project/requirements.txt

      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python tourism_project/hosting/hosting.py
